name: merge

on:
  push:
    branches:
      - master

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -XX:MaxMetaspaceSize=512m' -Dorg.gradle.parallel=true"
    steps: # action or script execute
      - uses: actions/checkout@v4
        with: # default : 1, all : 0
          fetch-depth: 1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle  # use ~/.gradle/cache
      - name: Print env
        run: printenv
      - name : Run test
        run: |
          ./gradlew -p "inventory" test

  deploy:
    name: Deploy
    needs: test-and-analyze
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo 'Deploying...'
          echo 'Deployed!'
